home/urls.py
from django.urls import path
from . import views

app_name="home"
urlpatterns = [
    path('',views.HomeView.as_view(),name="home"),
    path('about/',views.AboutView.as_view(),name="about"),
    path('contact/',views.ContactView.as_view(),name="contact"),
    path('search/',views.SearchView.as_view(),name="search"),



]

myStore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('shop/',include('shop.urls',namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += None

shop/urls.py
from django.urls import path
from . import views

app_name="shop"
urlpatterns = [
    path('products/',views.ProductListView.as_view(),name='product_list'),
    path('categories/<int:category_id>/',views.CategorytListView.as_view(),name='category_list'),

    path('create/',views.OrderCreateView.as_view(),name='create_order'),
    path('detail/<int:order_id>',views.OrderDetailView.as_view(),name='order_detail'),
    path('cart/',views.CartView.as_view(),name="cart"),

    path('<slug:slug>/',views.ProductDetailView.as_view(),name='product_detail'),
    path('cart/add/<int:product_id>/',views.CartAddView.as_view(),name='cart_add'),
    path('cart/remove/<int:product_id>/',views.CartRemoveView.as_view(),name='cart_remove'),
    path('create/',views.OrderCreateView.as_view(),name='create_order'),
    path('detail/',views.OrderDetailView.as_view(),name='order_detail'),
    path('pay/<int:order_id>/',views.OrderPayView.as_view(),name='order_pay'),
    path('verify/',views.OrderVerifyView.as_view(),name='order_verify'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import View
from shop.models import Product,Category
from django.core.paginator import Paginator

class HomeView(View):
    def get(self,request):
        products=Product.objects.filter(available=True)
        page_number = request.GET.get("page")
        paginator=Paginator(products,1)
        objects_list=paginator.get_page(page_number) 

        categories=Category.objects.all()
       
        context={
            'products':objects_list,
            'categories':categories
        }
        return render(request,'home/home.html',context)

class AboutView(View):
    def get(self,request):

        return render(request,'home/about.html')

class ContactView(View):
    def get(self,request):

        return render(request,'home/contact.html')

class SearchView(View):
    def get(self,request):
        search=request.GET.get('searchboxx')
        products= Product.objects.filter(name__icontains=search)|Product.objects.filter(description__icontains=search)
        return render(request,'home/search.html',{'products':products})

home/templates/home/about.html
{% extends 'base.html'%}
{% load static %}


{% block title %}  درباره ما{% endblock %}


{% block navbar %}
{% include 'inc/navbar.html' %}

{% endblock %}


{% block content %}
{% endblock %}


                     
      


  






  







{% block footer %}
<footer class="bg-dark" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-success border-bottom pb-3 border-light logo">Zay Shop</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li>
                            <i class="fas fa-map-marker-alt fa-fw"></i>
                            123 Consectetur at ligula 10660
                        </li>
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Products</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="#">Luxury</a></li>
                        <li><a class="text-decoration-none" href="#">Sport Wear</a></li>
                        <li><a class="text-decoration-none" href="#">Men's Shoes</a></li>
                        <li><a class="text-decoration-none" href="#">Women's Shoes</a></li>
                        <li><a class="text-decoration-none" href="#">Popular Dress</a></li>
                        <li><a class="text-decoration-none" href="#">Gym Accessories</a></li>
                        <li><a class="text-decoration-none" href="#">Sport Shoes</a></li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="#">Home</a></li>
                        <li><a class="text-decoration-none" href="#">About Us</a></li>
                        <li><a class="text-decoration-none" href="#">Shop Locations</a></li>
                        <li><a class="text-decoration-none" href="#">FAQs</a></li>
                        <li><a class="text-decoration-none" href="#">Contact</a></li>
                    </ul>
                </div>

            </div>

            <div class="row text-light mb-4">
                <div class="col-12 mb-3">
                    <div class="w-100 my-3 border-top border-light"></div>
                </div>
                <div class="col-auto me-auto">
                    <ul class="list-inline text-left footer-icons">
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i class="fab fa-twitter fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.linkedin.com/"><i class="fab fa-linkedin fa-lg fa-fw"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-auto">
                    <label class="sr-only" for="subscribeEmail">Email address</label>
                    <div class="input-group mb-2">
                        <input type="text" class="form-control bg-dark border-light" id="subscribeEmail" placeholder="Email address">
                        <div class="input-group-text btn-success text-light">Subscribe</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="w-100 bg-black py-3">
            <div class="container">
                <div class="row pt-2">
                    <div class="col-12">
                        <p class="text-left text-light">
                            Copyright &copy; 2021 Company Name 
                            | Designed by <a rel="sponsored" href="https://templatemo.com" target="_blank">TemplateMo</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </footer>

{% endblock %}

home/templates/home/contact.html
{% extends 'base.html'%}
{% load static %}


{% block title %}  ارتباط با ما{% endblock %}


{% block navbar %}
{% include 'inc/navbar.html' %}

{% endblock %}


{% block content %}
{% endblock %}


                     
      


  






  







{% block footer %}
<footer class="bg-dark" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-success border-bottom pb-3 border-light logo">Zay Shop</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li>
                            <i class="fas fa-map-marker-alt fa-fw"></i>
                            123 Consectetur at ligula 10660
                        </li>
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Products</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="#">Luxury</a></li>
                        <li><a class="text-decoration-none" href="#">Sport Wear</a></li>
                        <li><a class="text-decoration-none" href="#">Men's Shoes</a></li>
                        <li><a class="text-decoration-none" href="#">Women's Shoes</a></li>
                        <li><a class="text-decoration-none" href="#">Popular Dress</a></li>
                        <li><a class="text-decoration-none" href="#">Gym Accessories</a></li>
                        <li><a class="text-decoration-none" href="#">Sport Shoes</a></li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="#">Home</a></li>
                        <li><a class="text-decoration-none" href="#">About Us</a></li>
                        <li><a class="text-decoration-none" href="#">Shop Locations</a></li>
                        <li><a class="text-decoration-none" href="#">FAQs</a></li>
                        <li><a class="text-decoration-none" href="#">Contact</a></li>
                    </ul>
                </div>

            </div>

            <div class="row text-light mb-4">
                <div class="col-12 mb-3">
                    <div class="w-100 my-3 border-top border-light"></div>
                </div>
                <div class="col-auto me-auto">
                    <ul class="list-inline text-left footer-icons">
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i class="fab fa-twitter fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.linkedin.com/"><i class="fab fa-linkedin fa-lg fa-fw"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-auto">
                    <label class="sr-only" for="subscribeEmail">Email address</label>
                    <div class="input-group mb-2">
                        <input type="text" class="form-control bg-dark border-light" id="subscribeEmail" placeholder="Email address">
                        <div class="input-group-text btn-success text-light">Subscribe</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="w-100 bg-black py-3">
            <div class="container">
                <div class="row pt-2">
                    <div class="col-12">
                        <p class="text-left text-light">
                            Copyright &copy; 2021 Company Name 
                            | Designed by <a rel="sponsored" href="https://templatemo.com" target="_blank">TemplateMo</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </footer>

{% endblock %}

home/templates/home/home.html
{% extends 'base.html'%}
{% load static %}


{% block title %}  فروشگاه{% endblock %}


{% block navbar %}
{% include 'inc/navbar.html' %}

{% endblock %}
{% block Modal %}
   

 
<div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="w-100 pt-1 mb-5 text-right">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="" method="get" class="modal-content modal-body border-0 p-0">
                <div class="input-group mb-2">
                    <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search ...">
                    <button type="submit" class="input-group-text bg-success text-light">
                        <i class="fa fa-fw fa-search text-white"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
    {% endblock %}



 {% block Hero %}

 {% for product in products %}

    <div id="template-mo-zay-hero-carousel" class="carousel slide" data-bs-ride="carousel">
        

        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="container">
                    <div class="row p-5">
                       
                        <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="{{product.image.url}}" alt="">
                        </div>
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left align-self-center">
                                <a href="{% url 'shop:product_detail' product.slug %}">
                                <h3 class="h2">{{product.name}}</h3>

                                <p>
                                    {{product.description|truncatewords:10}}
                                </p>
                            </a>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
           
            
                
        </div>
        {% endfor %}
        {% if products.has_other_pages %}
        {% if products.has_previous %}

        <a class="carousel-control-prev text-decoration-none w-auto ps-3" href="?page={{ products.previous_page_number }}" role="button" data-bs-slide="prev">
            <i class="fas fa-chevron-left"></i>
        </a>

        {% else %}

        {% endif %}
        {% if products.has_next %}

        <a class="carousel-control-next text-decoration-none w-auto pe-3" href="?page={{ products.next_page_number }}" role="button" data-bs-slide="next">
            <i class="fas fa-chevron-right"></i>
        </a>
        {% else %}

        {% endif %}
        {% endif %}
    </div>
  



  
    {% if products.has_other_pages %}
    <div style="text-align: center;">
<ul class="ul-1">

  {% if products.has_previous %}
 
<li data-bs-target="#template-mo-zay-hero-carousel"  class="li-1"><a href="?page={{ products.previous_page_number }}" >&laquo;</a></li>

  {% else %}
    <li class="li-1"><span>&laquo;</span></li>
  {% endif %}


  {% for i in products.paginator.page_range %}
    {% if products.number == i %}
      <li class="li-1"><span>{{ i }} <span class="sr-only"></span></span></li>
    {% else %}
      <li class="li-1"><a href="?page={{ i }}" >{{ i }}</a></li>
    {% endif %}
  {% endfor %}

  {% if products.has_next %}
    <li class="li-1"><a href="?page={{ products.next_page_number }}">&raquo;</a></li>
  {% else %}
    <li class="li-1"><span>&raquo;</span></li>
  {% endif %}
</ul>


</div>
<br>
<br>

{% endif %}
    

    {% endblock %}



  {% block categories %}
    <section class="container py-5">

        <div class="row text-center pt-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1">دسته بندی محصولات</h1>
                <p>
                  
                </p>
            </div>
        </div>

        <div class="row">
            {% for category in categories %}

            <div class="col col-6 p-5 mt-3">
                <a href="{% url 'shop:category_list' category.id %}"> 
                                   <h5 class="text-center mt-3 mb-3">{{category.name}}</h5>
                </a>
            </div>
            {% endfor %}

           
        </div>

    </section>
    {% endblock %}


{% block content %}


    {% endblock %}

home/templates/home/search.html
{% extends 'base.html'%}
{% load static %}


{% block title %}  فروشگاه{% endblock %}


{% block navbar %}
{% include 'inc/navbar.html' %}
 
{% endblock %}
{% block content %}

<div class="container">
	
    <br>
    <br>
    <h2 class="text-center">نتایج جستجو</h2>
    
{% for p in products %}
<div class="row">
    <div class="col-md-12 text-center">
        <a  href="{% url 'shop:product_detail' p.slug %}">
         <span style="color:black">{{p.name}}</span>   

        </a>

</div>
</div>
{% endfor %}




    


</div>
    {% endblock %}








{% block footer %}
<footer class="bg-dark" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-success border-bottom pb-3 border-light logo">Zay Shop</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li>
                            <i class="fas fa-map-marker-alt fa-fw"></i>
                            123 Consectetur at ligula 10660
                        </li>
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Products</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="#">Luxury</a></li>
                        <li><a class="text-decoration-none" href="#">Sport Wear</a></li>
                        <li><a class="text-decoration-none" href="#">Men's Shoes</a></li>
                        <li><a class="text-decoration-none" href="#">Women's Shoes</a></li>
                        <li><a class="text-decoration-none" href="#">Popular Dress</a></li>
                        <li><a class="text-decoration-none" href="#">Gym Accessories</a></li>
                        <li><a class="text-decoration-none" href="#">Sport Shoes</a></li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="#">Home</a></li>
                        <li><a class="text-decoration-none" href="#">About Us</a></li>
                        <li><a class="text-decoration-none" href="#">Shop Locations</a></li>
                        <li><a class="text-decoration-none" href="#">FAQs</a></li>
                        <li><a class="text-decoration-none" href="#">Contact</a></li>
                    </ul>
                </div>

            </div>

            <div class="row text-light mb-4">
                <div class="col-12 mb-3">
                    <div class="w-100 my-3 border-top border-light"></div>
                </div>
                <div class="col-auto me-auto">
                    <ul class="list-inline text-left footer-icons">
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i class="fab fa-twitter fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.linkedin.com/"><i class="fab fa-linkedin fa-lg fa-fw"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-auto">
                    <label class="sr-only" for="subscribeEmail">Email address</label>
                    <div class="input-group mb-2">
                        <input type="text" class="form-control bg-dark border-light" id="subscribeEmail" placeholder="Email address">
                        <div class="input-group-text btn-success text-light">Subscribe</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="w-100 bg-black py-3">
            <div class="container">
                <div class="row pt-2">
                    <div class="col-12">
                        <p class="text-left text-light">
                            Copyright &copy; 2021 Company Name 
                            | Designed by <a rel="sponsored" href="https://templatemo.com" target="_blank">TemplateMo</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </footer>

{% endblock %}