home/urls.py
from django.urls import path
from . import views

app_name="home"
urlpatterns = [
    path('',views.HomeView.as_view(),name="home"),
    path('about/',views.AboutView.as_view(),name="about"),
    path('contact/',views.ContactView.as_view(),name="contact"),
    path('search/',views.SearchView.as_view(),name="search"),



]

myStore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('shop/',include('shop.urls',namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += None

shop/urls.py
from django.urls import path
from . import views

app_name="shop"
urlpatterns = [
    path('products/',views.ProductListView.as_view(),name='product_list'),
    path('categories/<int:category_id>/',views.CategorytListView.as_view(),name='category_list'),

    path('create/',views.OrderCreateView.as_view(),name='create_order'),
    path('detail/<int:order_id>',views.OrderDetailView.as_view(),name='order_detail'),
    path('cart/',views.CartView.as_view(),name="cart"),

    path('<slug:slug>/',views.ProductDetailView.as_view(),name='product_detail'),
    path('cart/add/<int:product_id>/',views.CartAddView.as_view(),name='cart_add'),
    path('cart/remove/<int:product_id>/',views.CartRemoveView.as_view(),name='cart_remove'),
    path('create/',views.OrderCreateView.as_view(),name='create_order'),
    path('detail/',views.OrderDetailView.as_view(),name='order_detail'),
    path('pay/<int:order_id>/',views.OrderPayView.as_view(),name='order_pay'),
    path('verify/',views.OrderVerifyView.as_view(),name='order_verify'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from accounts.models import User



class Category(models.Model):
    name=models.CharField(max_length=200)
    slug=models.SlugField(max_length=200,unique=True)

    class Meta:
        ordering=('name',)
        verbose_name='دسته بندی'
        verbose_name_plural='دسته بندی ها'

    def __str__(self):
        return self.name    


class Product(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE,related_name='products')
    name=models.CharField(max_length=300)
    slug=models.SlugField(max_length=250,unique=True)
    image=models.ImageField(upload_to='products/')
    description=models.TextField()
    price=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name='محصول  '
        verbose_name_plural=' محصولات'
        

    def __str__(self):
        return self.name 
        
    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.slug,])



class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='orders')
    paid=models.BooleanField(default=False)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)

    class Meta:
        ordering=('paid','-updated')
        verbose_name='سفارش  '
        verbose_name_plural=' سفارش ها'
    def __str__(self):
        return f'{self.user} - {str(self.id)}'   

    def get_total_price(self):
        return sum(item.get_cost() for item in self.items.all())          

class OrderItem(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE,related_name='items')
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    price=models.IntegerField()
    quantity=models.IntegerField(default=1)

    def __str__(self):
        return str(self.id)
        
    def get_cost(self):
        return self.price*self.quantity

shop/forms.py
from django import forms

class CartAddForm(forms.Form):
    quantity=forms.IntegerField(label='تعداد',min_value=1,max_value=5,widget=forms.NumberInput(attrs={'class': 'form-row input-text'}))
    

shop/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views import View
from django.urls import reverse
from .models import Product,Category,OrderItem,Order
from django.core.paginator import Paginator
from .forms import CartAddForm
from .cart import Cart 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect
import requests
import json


class ProductListView(View):
    def get(self,request):
        products=Product.objects.filter(available=True)
        page_number = request.GET.get("page")
        paginator=Paginator(products,3)
        objects_list=paginator.get_page(page_number) 
        return render(request,'shop/productlist.html',{'products':objects_list})

class CategorytListView(View):
    def get(self,request,category_id):
        category=Category.objects.get(id=category_id)
        products=Product.objects.filter(category=category)
        return render(request,'shop/categorylist.html',{'category':category,'products':products})



class ProductDetailView(View):
    def get(self,request,slug):
        product=get_object_or_404(Product,slug=slug)
        form=CartAddForm()
        context={
            'product':product,
            'form':form

        }
        return render(request,'shop/productdetail.html',context)
        

class CartView(View):
    def get(self,request):
        cart=Cart(request)
        return render(request,'shop/cart.html',{'cart':cart})

class CartAddView(View):
    def post(self,request,product_id):
        cart=Cart(request)
        product=get_object_or_404(Product,id=product_id)
        form=CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product,form.cleaned_data['quantity'])
            return redirect('shop:cart')
    
class CartRemoveView(View):
    def get(self,request,product_id):
        cart=Cart(request)
        product=get_object_or_404(Product,id=product_id)
        cart.remove(product)
        return redirect('shop:cart')


class OrderDetailView(LoginRequiredMixin,View):
    def get(self,request,order_id):
        order=get_object_or_404(Order,id=order_id)
        return render(request,'shop/order.html',{'order':order})



class OrderCreateView(LoginRequiredMixin,View):
    def get(self,request):
        cart=Cart(request)
        order=Order.objects.create(user=request.user)
        for item in cart:
            OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
        cart.clear()
        return redirect('shop:order_detail',order.id)


MERCHANT = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
ZP_API_REQUEST = "https://api.zarinpal.com/pg/v4/payment/request.json"
ZP_API_VERIFY = "https://api.zarinpal.com/pg/v4/payment/verify.json"
ZP_API_STARTPAY = "https://www.zarinpal.com/pg/StartPay/{authority}"
amount = 11000 # Rial / Required
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید" # Required
CallbackURL = 'http://localhost:8000/shop/verify/'

class OrderPayView(LoginRequiredMixin,View):
    def get(self,request,order_id):
        order=Order.objects.get(id=order_id)
        request.session['order_pay']={
            'order_id':order.id,
        }

        req_data = {

        "merchant_id": MERCHANT,
        "amount": amount,
        "callback_url": CallbackURL,
        "description": description,
        "metadata": {"mobile": request.user.phone_number, "email": request.user.email}
        }

        req_header = {"accept": "application/json", "content-type": "application/json'"}

        req = requests.post(url=ZP_API_REQUEST, data=json.dumps( req_data), headers=req_header)
        authority = req.json()['data']['authority']
        if len(req.json()['errors']) == 0:
            return redirect(ZP_API_STARTPAY.format(authority=authority))
        else:
            e_code = req.json()['errors']['code']
            e_message = req.json()['errors']['message']
            return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")



    

class OrderVerifyView(LoginRequiredMixin,View):
    def get(self,request):
        order_id=request.session['order_pay']['order_id']
        order=Order.objects.get(id=int(order_id))
        t_status = request.GET.get('Status')
        t_authority = request.GET['Authority']
        if request.GET.get('Status') == 'OK':
            req_header = {"accept": "application/json","content-type": "application/json'"}
            req_data = {
                    "merchant_id": MERCHANT,
                    "amount": order.get_total_price(),
                    "authority": t_authority}

            req = requests.post(url=ZP_API_VERIFY, data=json.dumps(req_data), headers=req_header)
            if len(req.json()['errors']) == 0:
                t_status = req.json()['data']['code']
                if t_status == 100:
                    order.paid=True
                    order.save()
                    return HttpResponse('Transaction success.\nRefID: ' + str(req.json()['data']['ref_id']))
                elif t_status == 101:
                    return HttpResponse('Transaction submitted : ' + str(req.json()['data']['message']))
                else:
                    return HttpResponse('Transaction failed.\nStatus: ' + str(req.json()['data']['message']))        
            else:
                e_code = req.json()['errors']['code']
                e_message = req.json()['errors']['message']
                return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")

        else:
            return HttpResponse('Transaction failed or canceled by user')

shop/templates/shop/cart.html
{% extends 'base.html' %}

{% block content %}
{% include 'inc/navbar.html' %}

<table class="table  table-hover table-bordered border-primary">
    <thead>
      <tr>
        <th class="text-center" scope="col">شماره</th>
        <th class="text-center" scope="col">نام</th>
        <th class="text-center" scope="col">تعداد</th>
        <th class="text-center" scope="col">هزینه </th>
        <th class="text-center" scope="col">هزینه نهایی</th>
        <th class="text-center" scope="col"> حذف</th>

      </tr>
    </thead>
    <tbody>
    {% for item in cart %}
      <tr>
        <th class="text-center" scope="row">{{forloop.counter}}</th>
        <td class="text-center">{{item.product}}</td>
        <td class="text-center">{{item.quantity}}</td>
        <td class="text-center">{{item.price}}</td>
        <td class="text-center">{{item.total_price}}</td>
        <td class="text-center"><a class='btn btn-danger' href="{% url 'shop:cart_remove' item.product.id %}">حذف</a></td>

      </tr>

   {% endfor %}
   <tr>
    <th class="text-center" scope="row">هزینه نهایی </th>
    <td class="text-center">{{cart.get_total_price}}</td>

  </tr>
     
    </tbody>
  </table>
  <a class='btn btn-primary' href="{% url 'shop:create_order' %}">ثبت</a>

  {% include 'inc/footer.html' %}
{% endblock %}

shop/templates/shop/categorylist.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/shopcss.css' %}">



{% block content %}


{% include 'inc/navbar.html' %}


{% for product in products %}
{{product.products}}
</br>
</br>

<div class="container">

    <div class="col-xs-12 col-md-10">

                    <!-- First product box start here-->
                    <div class="prod-info-main prod-wrap clearfix">
    
    <div class="row">
    
                               <div class="col-md-5 col-sm-8 col-xs-12">
    
    <div class="product-image">
    
                                 <img src="{{product.image.url}}" class="img-responsive">
    
                                   <span class="tag2 hot">
    
                                   </span>
    
                           </div>
    
                      </div>
    
         <div class="col-md-7 col-sm-12 col-xs-12">
    
                      <div class="product-deatil">
    
                                   <h5 class="name">
    
    
        <a href="{{ product.get_absolute_url }}" class="card-title">{{product.name}}</a>    
    
                                   
    
                                 
    
                            </h5>
    
                                <p class="price-container">
                                    <div>   <div>{{product.price}}</div>
                                    <span>ریال</span>
                                </div>
                                    

    
                               </p>
    
                  <span class="tag1"></span>
    
       </div>
    
       <div class="description">
    
          <p>{{product.description}} </p>
    
       </div>
    
          <div class="product-info smart-form">
    
             <div class="row"
    
        <div class="col-md-12">
    <div>
              <a href="{% url 'shop:product_detail' product.slug  %}" class=" btn btn-danger">اضافه به سبد خرید</a>
    
                 <a href="javascript:void(0);" class="btn btn-info">اطلاعات بیشتر</a>
                </div>
           </div>
    
          <div class="col-md-12">
    
             <div class="rating">امتیاز دهی:
    
              <label for="stars-rating-5"><i class="fa fa-star text-danger"></i></label>
    
              <label for="stars-rating-4"><i class="fa fa-star text-danger"></i></label>
    
              <label for="stars-rating-3"><i class="fa fa-star text-danger"></i></label>
    
              <label for="stars-rating-2"><i class="fa fa-star text-warning"></i></label>
    
              <label for="stars-rating-1"><i class="fa fa-star text-warning"></i></label>
    
             </div>
    
           </div>
           <br>
           <hr>
    
        </div>
    
       </div>
    
      </div>
    
    </div>
     </div>
    
     <!-- end product -->
    
    </div>
    </div>
    
    </div>



  
{% endfor %}


{% if products.has_other_pages %}
    <div style="text-align: center;">
<ul class="ul-1">

  {% if products.has_previous %}

<li class="li-1"><a href="?page={{ products.previous_page_number }}" >&laquo;</a></li>

  {% else %}
    <li class="li-1"><span>&laquo;</span></li>
  {% endif %}


  {% for i in products.paginator.page_range %}
    {% if products.number == i %}
      <li class="li-1"><span>{{ i }} <span class="sr-only"></span></span></li>
    {% else %}
      <li class="li-1"><a href="?page={{ i }}" >{{ i }}</a></li>
    {% endif %}
  {% endfor %}

  {% if products.has_next %}
    <li class="li-1"><a href="?page={{ products.next_page_number }}">&raquo;</a></li>
  {% else %}
    <li class="li-1"><span>&raquo;</span></li>
  {% endif %}
</ul>
</div>
<br>
<br>

{% endif %}

  {% endblock %}

shop/templates/shop/order.html
{% extends 'base.html' %}

{% block content %}
{% include 'inc/navbar.html' %}
<h3>مبلغ نهایی</h3>

<p> {{order.get_total_price}}</p>
<a class="btn btn-primary " href="{% url 'shop:order_pay' order.id  %}">
    پرداخت
</a>

{% endblock %}

shop/templates/shop/productdetail.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/shopcss.css' %}">



{% block content %}


 
{% include 'inc/navbar.html' %}


</br>
</br>

<div class="container">

    <div class="col-xs-12 col-md-10">

                    <!-- First product box start here-->
                    <div class="prod-info-main prod-wrap clearfix">
    
    <div class="row">
    
                               <div class="col-md-5 col-sm-8 col-xs-12">
    
    <div class="product-image">
    
                                 <img src="{{product.image.url}}" class="img-responsive">
    
                                   <span class="tag2 hot">
    
                                   </span>
    
                           </div>
    
                      </div>
    
         <div class="col-md-7 col-sm-12 col-xs-12">
    
                      <div class="product-deatil">
    
                                   <h5 class="name">
    
    
        <a href="{{ product.get_absolute_url }}" class="card-title">{{product.name}}</a>    
    
                                   
    
                                   <a href="#">
    
                                   <span>Product Category</span>
    
                                   </a>
    
                            </h5>
    
                                <p class="price-container">
                                    <div>   <div>{{product.price}}</div>
                                    <span>ریال</span>
                                </div>
                                    

    
                               </p>
    
                  <span class="tag1"></span>
    
       </div>
    
       <div class="description">
    
          <p>{{product.description}} </p>
          <br>
        
    
       </div>
    
          <div class="product-info smart-form">
    
             <div class="row"
    
        <div class="col-md-12">
    <div>
        <form action="{% url 'shop:cart_add' product.id %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input  class=" btn btn-danger" type="submit" value="اضافه به سبد خرید">
          </form>
    
                </div>
           </div>
    
          <div class="col-md-12">
    
             <div class="rating">امتیاز دهی:
    
              <label for="stars-rating-5"><i class="fa fa-star text-danger"></i></label>
    
              <label for="stars-rating-4"><i class="fa fa-star text-danger"></i></label>
    
              <label for="stars-rating-3"><i class="fa fa-star text-danger"></i></label>
    
              <label for="stars-rating-2"><i class="fa fa-star text-warning"></i></label>
    
              <label for="stars-rating-1"><i class="fa fa-star text-warning"></i></label>
    
             </div>
    
           </div>
           <br>
           <hr>
    
        </div>
    
       </div>
    
      </div>
    
    </div>
     </div>
    
     <!-- end product -->
    
    </div>
    </div>
    
    </div>
<br>
<br>

  {% endblock %}

shop/templates/shop/productlist.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/shopcss.css' %}">



{% block content %}


{% include 'inc/navbar.html' %}


{% for product in products %}
</br>
</br>

<div class="container">

    <div class="col-xs-12 col-md-10">

                    <!-- First product box start here-->
                    <div class="prod-info-main prod-wrap clearfix">
    
    <div class="row">
    
                               <div class="col-md-5 col-sm-8 col-xs-12">
    
    <div class="product-image">
    
                                 <img src="{{product.image.url}}" class="img-responsive">
    
                                   <span class="tag2 hot">
    
                                   </span>
    
                           </div>
    
                      </div>
    
         <div class="col-md-7 col-sm-12 col-xs-12">
    
                      <div class="product-deatil">
    
                                   <h5 class="name">
    
    
        <a href="{{ product.get_absolute_url }}" class="card-title">{{product.name}}</a>    
    
                                   
    
                                 
    
                            </h5>
    
                                <p class="price-container">
                                    <div>   <div>{{product.price}}</div>
                                    <span>ریال</span>
                                </div>
                                    

    
                               </p>
    
                  <span class="tag1"></span>
    
       </div>
    
       <div class="description">
    
          <p>{{product.description}} </p>
    
       </div>
    
          <div class="product-info smart-form">
    
             <div class="row"
    
        <div class="col-md-12">
    <div>
              <a href="{% url 'shop:product_detail' product.slug  %}" class=" btn btn-danger">اضافه به سبد خرید</a>
    
                 <a href="javascript:void(0);" class="btn btn-info">اطلاعات بیشتر</a>
                </div>
           </div>
    
          <div class="col-md-12">
    
             <div class="rating">امتیاز دهی:
    
              <label for="stars-rating-5"><i class="fa fa-star text-danger"></i></label>
    
              <label for="stars-rating-4"><i class="fa fa-star text-danger"></i></label>
    
              <label for="stars-rating-3"><i class="fa fa-star text-danger"></i></label>
    
              <label for="stars-rating-2"><i class="fa fa-star text-warning"></i></label>
    
              <label for="stars-rating-1"><i class="fa fa-star text-warning"></i></label>
    
             </div>
    
           </div>
           <br>
           <hr>
    
        </div>
    
       </div>
    
      </div>
    
    </div>
     </div>
    
     <!-- end product -->
    
    </div>
    </div>
    
    </div>



  
{% endfor %}


{% if products.has_other_pages %}
    <div style="text-align: center;">
<ul class="ul-1">

  {% if products.has_previous %}

<li class="li-1"><a href="?page={{ products.previous_page_number }}" >&laquo;</a></li>

  {% else %}
    <li class="li-1"><span>&laquo;</span></li>
  {% endif %}


  {% for i in products.paginator.page_range %}
    {% if products.number == i %}
      <li class="li-1"><span>{{ i }} <span class="sr-only"></span></span></li>
    {% else %}
      <li class="li-1"><a href="?page={{ i }}" >{{ i }}</a></li>
    {% endif %}
  {% endfor %}

  {% if products.has_next %}
    <li class="li-1"><a href="?page={{ products.next_page_number }}">&raquo;</a></li>
  {% else %}
    <li class="li-1"><span>&raquo;</span></li>
  {% endif %}
</ul>
</div>
<br>
<br>

{% endif %}

  {% endblock %}