accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns=[
    path('register/',views.UserRegisterView.as_view(), name='user_register'),
    path('verify/',views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/',views.UserLoginView.as_view(), name='user_login'),
    path('logout/',views.UserLogoutView.as_view(), name='user_logout'),

    
]

home/urls.py
from django.urls import path
from . import views

app_name="home"
urlpatterns = [
    path('',views.HomeView.as_view(),name="home"),
    path('about/',views.AboutView.as_view(),name="about"),
    path('contact/',views.ContactView.as_view(),name="contact"),
    path('search/',views.SearchView.as_view(),name="search"),



]

myStore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('shop/',include('shop.urls',namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += None

shop/urls.py
from django.urls import path
from . import views

app_name="shop"
urlpatterns = [
    path('products/',views.ProductListView.as_view(),name='product_list'),
    path('categories/<int:category_id>/',views.CategorytListView.as_view(),name='category_list'),

    path('create/',views.OrderCreateView.as_view(),name='create_order'),
    path('detail/<int:order_id>',views.OrderDetailView.as_view(),name='order_detail'),
    path('cart/',views.CartView.as_view(),name="cart"),

    path('<slug:slug>/',views.ProductDetailView.as_view(),name='product_detail'),
    path('cart/add/<int:product_id>/',views.CartAddView.as_view(),name='cart_add'),
    path('cart/remove/<int:product_id>/',views.CartRemoveView.as_view(),name='cart_remove'),
    path('create/',views.OrderCreateView.as_view(),name='create_order'),
    path('detail/',views.OrderDetailView.as_view(),name='order_detail'),
    path('pay/<int:order_id>/',views.OrderPayView.as_view(),name='order_pay'),
    path('verify/',views.OrderVerifyView.as_view(),name='order_verify'),
]

templates/inc/footer.html
    <!-- Start Footer -->
    <footer class="bg-dark" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-success border-bottom pb-3 border-light logo">فروشگاه  کیف و کفش بیتا </h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li>
                            <i class="fas fa-map-marker-alt fa-fw"></i>
                            تهران ، بعد از پارک ملت،کوچه تورج                        </li>
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none" href="tel:010-020-0340">021-44330000</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none" href="mailto:info@company.com">Bitastoretop@bitaco.com</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">فروشگاه</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="{% url 'shop:product_list' %}">محصولات</a></li>
                        <li><a class="text-decoration-none" href="{% url 'shop:cart' %}">  سبد خرید </a></li>
                        
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light"> اطلاعات</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="#">صفحه اصلی</a></li>
                        <li><a class="text-decoration-none" href="#"> درباره ما</a></li>
                        <li><a class="text-decoration-none" href="#">ارتباط باما</a></li>
                    </ul>
                </br>
            </br>
            </br>
                </div>
         
            </div>

      

 

    </footer>

templates/inc/messages.html
{% if messages %}
{% for msg in messages %}
<p class="alert alert-success text-center">{{msg}}</p>

{% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
    <div class="container text-light">
        <div class="w-100 d-flex justify-content-between">
            <div>
                <i class="fa fa-envelope mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:info@company.com">Bitastoretop@bitaco.com</a>
                <i class="fa fa-phone mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none" href="tel:010-020-0340">021-443330000</a>
            </div>
            <div>
                <a class="text-light" href="https://fb.com/templatemo" target="_blank" rel="sponsored"><i class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://twitter.com/" target="_blank"><i class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin fa-sm fa-fw"></i></a>
            </div>
        </div>
    </div>
</nav>


<nav class="navbar navbar-expand-lg navbar-light shadow">
    <div class="container d-flex justify-content-between align-items-center">

        <a class="navbar-brand text-success logo h1 align-self-center" href="{% url 'home:home' %}">
         BTA
        </a>

        <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
            <div class="flex-fill">
                <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:home' %}">صفحه اصلی</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:about' %}">درباره ما</a>
                    </li>
                   
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:contact' %}">ارتباط با ما</a>
                    </li>
                </ul>
            </div>
            <div class="text-center">
                <div class=" flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">
                    <form role="search" method="get" class="search-box" action="{% url 'home:search' %}" >

                    <div class="input-group">
                        <input type="text" class="form-control" id="inputMobileSearch"  name="searchboxx" placeholder="جستجو ...">
                        <div class="input-group-text">
                            <button ><i class="fa fa-fw fa-search"></i></button>
                        </div>
                    </form>
                    </div>
                </div>
                <ul style="list-style: none;">
                    

              
                {% if request.user.is_authenticated %}
              
                <li style="display: inline;">
                    <a class="nav-icon position-relative text-decoration-none" href="{% url 'shop:cart' %}">
                       
                        <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>
                        <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">{{cart_key|length}}</span>
                    </a>
                </li>
            

               <li style="display: inline;">
                <a class="nav-icon position-relative text-decoration-none" href="{% url 'accounts:user_logout' %}">
                    
                    <i class="fa fa-fw fa-user text-dark mr-3"></i>
                    خروج
                </a>
               </li>

                {% else %}
                <div class="row justify-content-center">
                   
            <div class="col col-md-4">
                <li class="nav-item dropdown style="display: inline;">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      ورود
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'accounts:user_login' %}">ورود</a></li>
                      <li><a class="dropdown-item" href="{% url 'accounts:user_register' %}"> ثبت نام</a></li>
                    </ul>
                  </li>
                </div>
                </div>
                

                {% endif %}
               
                    
             
             

            </ul>
            </div>
        </div>

    </div>
</nav>